### PR TITLE
较多更新,增加一些通用功能,如 "热替换,mock,oidc认证, 调试组件"等

### PR DESCRIPTION
**Pull request by tearf001**
1.增加开发插件 customize-cra-react-refresh, 使用 热替换而不是热重载
2. 添加 mock [MSW 即 mock service work](https://mswjs.io/) 模拟服务请求特性
3. 用户登录移入 mock
4. 增强部分ts类型, 并引入一些typescript类型
5. 增加devServer配置选项, 并加入更灵活的proxy配置 ,并修改不可用的proxy配置
6. 修改axios响应转换,使得更符合一般的情况. 把"网络异常" 改为 "请求失败"避免歧义
7. 增加 oidc登录,和原功能并行
8. 增加.env配置文件, 配置oidc信息
9. 调整 package.json 的 依赖和开发依赖错误位置 及一些需要的库如 oidc_client, redux-devtools
10. 增加Json查看组件 ,用于调试
11. 其他修改 和 代码格式自动修改( 有可能是因为编辑器或者prettier设置问题导致的 :(  )
image
image

### CODE REVIEW

**Comment by hsl947** [comment]
@tearf001 好的，非常感谢。我先review看看😉

**Comment by tearf001** [comment]
抱歉,这里面较多修改是没必要代码格式化变化引起的.
可能是注释了 'prettier/prettier': ['error', {parser: 'flow'}] ,(这句在webstorm上有bug, ..时间有点仓促没有研究)
后期再增加一些约定...

**Comment by tearf001** [comment]
# Prettier 官网 关于 Parser 的文档
Specify which parser to use.

Prettier automatically infers the parser from the input file path, so you shouldn’t have to change this setting.

Both the `babel` and `flow` parsers support the same set of JavaScript features (including Flow type annotations). They might differ in some edge cases, so if you run into one of those you can try `flow` instead of `babel`. Almost the same applies to `typescript` and `babel-ts`. `babel-ts` might support JavaScript features (proposals) not yet supported by TypeScript, but it’s less permissive when it comes to invalid code and less battle-tested than the `typescript` parser.

Valid options:

- `"babel"` (via [@babel/parser](https://github.com/babel/babel/tree/main/packages/babel-parser)) _Named `"babylon"` until v1.16.0_
- `"babel-flow"` (same as `"babel"` but enables Flow parsing explicitly to avoid ambiguity) _First available in v1.16.0_
- `"babel-ts"` (similar to `"typescript"` but uses Babel and its TypeScript plugin) _First available in v2.0.0_
- `"flow"` (via [flow-parser](https://github.com/facebook/flow/tree/master/src/parser))
- `"typescript"` (via [@typescript-eslint/typescript-estree](https://github.com/typescript-eslint/typescript-eslint)) _First available in v1.4.0_
- `"espree"` (via [espree](https://github.com/eslint/espree)) _First available in v2.2.0_
- `"meriyah"` (via [meriyah](https://github.com/meriyah/meriyah)) _First available in v2.2.0_
- `"acorn"` (via [acorn](https://github.com/acornjs/acorn)) _First available in v2.6.0_
- `"css"` (via [postcss-scss](https://github.com/postcss/postcss-scss) and [postcss-less](https://github.com/shellscape/postcss-less), autodetects which to use) _First available in v1.7.1_
- `"scss"` (same parsers as `"css"`, prefers postcss-scss) _First available in v1.7.1_
- `"less"` (same parsers as `"css"`, prefers postcss-less) _First available in v1.7.1_
- `"json"` (via [@babel/parser parseExpression](https://babeljs.io/docs/en/next/babel-parser.html#babelparserparseexpressioncode-options)) _First available in v1.5.0_
- `"json5"` (same parser as `"json"`, but outputs as [json5](https://json5.org/)) _First available in v1.13.0_
- `"json-stringify"` (same parser as `"json"`, but outputs like `JSON.stringify`) _First available in v1.13.0_
- `"graphql"` (via [graphql/language](https://github.com/graphql/graphql-js/tree/master/src/language)) _First available in v1.5.0_
- `"markdown"` (via [remark-parse](https://github.com/wooorm/remark/tree/main/packages/remark-parse)) _First available in v1.8.0_
- `"mdx"` (via [remark-parse](https://github.com/wooorm/remark/tree/main/packages/remark-parse) and [@mdx-js/mdx](https://github.com/mdx-js/mdx/tree/master/packages/mdx)) _First available in v1.15.0_
- `"html"` (via [angular-html-parser](https://github.com/ikatyang/angular-html-parser/tree/master/packages/angular-html-parser)) _First available in 1.15.0_
- `"vue"` (same parser as `"html"`, but also formats vue-specific syntax) _First available in 1.10.0_
- `"angular"` (same parser as `"html"`, but also formats angular-specific syntax via [angular-estree-parser](https://github.com/ikatyang/angular-estree-parser)) _First available in 1.15.0_
- `"lwc"` (same parser as `"html"`, but also formats LWC-specific syntax for unquoted template attributes) _First available in 1.17.0_
- `"yaml"` (via [yaml](https://github.com/eemeli/yaml) and [yaml-unist-parser](https://github.com/ikatyang/yaml-unist-parser)) _First available in 1.14.0_

下周再验证一下, 选择一个正确的parser

**Comment by tearf001** [comment]
我把 parser 的问题重新审视了一下, 发现对代码格式化并无影响.

我想代码格式化问题 出在你的开发环境.
  比如 prettier的配置 semi: false;  原代码中没有截取.

**Comment by tearf001** [comment]
应统一 prettier的解析器为 typescript. 如 prettierrc中的配置
原.eslintrc 配置为 flow.
我已经按最新的  PR 了

**Comment by tearf001** [comment]
升级 redux 原版 到 redux/toolkit, 减少大量模板代码,比如 actions, connect等
代码更容易跟踪和阅读, 具体来说:
- 1 不再需要 `connect`
```diff
- export default connect((state) => state, actions)(Header)
+ export default Header
```
- 2  props 不再需要扩展`ReduxProps `, 属性只保留组件相关
```diff
- interface Props - extends ReduxProps {
+ interface Props {
  option: object
  style?: object
}
```
- 3 不再需要声明 actions魔法字符串 , reducer 不再需要 `switch action.type`, 并把分离的 reducer / state / actionCreator 放入同一个 `redux 切片 slice`
```diff
- @/store/actrions
- @/store/reducers
- ...
+ @/store/slicers
```
slice 申明示例
```js
export const tabSlice = createSlice({
  name: 'tab',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setTabs: (state, action: PayloadAction<any[]>) => {
      state.curTab = action.payload
    },
    setCurrentTab: (state, action) => {
      state.currentTab = action.payload
    },
    setReloadPath: (state, action) => {
      state.reloadPath = action.payload
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder // 和其他 reducer互动, 或者自定义的 `AsyncThunk` Action
      .addCase(demoAsync.fulfilled, (state, action) => {
        state.status = 'idle'
        state.currentTab = action.payload
      })
  }
})
// actions
export const { setTabs, setCurrentTab, setReloadPath } = tabSlice.actions
// 强类型选择器
export const selectTabs = (state: RootState) => state.tab.curTab
export const selectCurrentTab = (state: RootState) => state.tab.currentTab
export const selectReloadPath = (state: RootState) => state.tab.reloadPath
```
- 4 `状态获取`和`行为派发`更加清晰可见, 并增强 redux state 类型提示
```diff
+ const dispatch = useAppDispatch()
+ const curTab = useAppSelector(selectTabs) // selectXxx 从 xxxSlice中导出
+ const reloadPath = useAppSelector(selectReloadPath) // selectXxx 从 xxxSlice中导出
... // 派发
+ dispatch(setReloadPath(pathname + search)) // setXxx 也从xxxSlice中导出

```

**Comment by hsl947** [comment]
@tearf001 很奇怪，我把你的分支合并过来了，但是 【 Contributors 】 怎么没有你头像？贡献者应该都会展示啊！
image

**Comment by hsl947** [comment]
@tearf001 刚刚合并代码后，我本地跑了一下，权限测试页面会报错，找不到 `userInfo`对象，你会这样吗
image

**Comment by hsl947** [comment]
@tearf001 你确实是漏改了权限测试页的，`selectUserInfo` 和 `setUserInfo`，导致报错了。我改提交了

**Pull request merged**
